### ISSUE TITLE
Dubbi sull'impostazione dell'AutomaCrud.java

### ISSUE THREAD

**Issue by marcobonaccorso** [ValeriaCom/CrudMac#1]
Abbiamo proseguito con la realizzazione del progetto arrivando fino alla gestione dei bottoni, ma abbiamo dei dubbi sulla corretta implementazione dell'AutomaCrud.java.

**Comment by luca-lezzerini** [comment]
Che dubbi?

**Comment by luca-lezzerini** [comment]
Per questi usate set visible
jButtonModifica.setEnabled(false);
        jButtonConferma.setEnabled(false);
        jButtonAnnulla.setEnabled(false);
        jButtonRimuovi.setEnabled(false);
        jButtonNuova.setEnabled(false);

**Comment by luca-lezzerini** [comment]
E spiegate meglio il senso del ticket
