### ISSUE TITLE
Click dei bottoni che non fanno un accidente

### ISSUE THREAD

**Issue by ValeriaCom** [ValeriaCom/CrudMac#2]
Nonostante aver implementato tutto (apparentemente in modo corretto), i cambiamenti nell'interfaccia al click di un bottone, non si avviano. Non sappiamo quindi come procedere.

**Comment by luca-lezzerini** [comment]
Ho clonato e ora vedo

**Comment by luca-lezzerini** [comment]
Se guardate il log dell'automa, facendo click su Nuova, come vedete non cambia stato:

Siamo nello stato crudmacedone.AutomaCrud$Ricerca@5e4f15c2
Ricevuto evento crudmacedone.NuovaEvent@335162a1
Siamo arrivati nello stato crudmacedone.AutomaCrud$Ricerca@5e4f15c2

Lo stato iniziale è giusto, l'evento è giusto ma lo stato finale è sbagliato -> classe Ricerca metodo next sbagliato. Ora vedo

**Comment by luca-lezzerini** [comment]
Il problema è che questo codice del metodo Next di Ricerca non ha la gestione dell'evento inatteso (ossia l'else degli if-else if).
@Override
        public void next(Event e) {
            if (e instanceof AddEvent) {
                stato = new Aggiungi();
            } else if (e instanceof SelezionaEvent) {
                stato = new Visualizza();
            } else if (e instanceof RicercaEvent) {
                stato = new Ricerca();
            }
        }

Mettendo l'else si vede che avete fatto confusione con gli eventi. Ora lo modifico.

**Comment by luca-lezzerini** [comment]
Confermo che il problema è lì.
Ora dovete fare:

1. Mettere l'else dove manca e stampare un messaggio di errore come il mio
2. Correggere l'errore (che io non ho corretto ... MUAH! MUAH! MUAH!)

Ho committato (vedasi commit 2414ce695852707feb8da7c46946d67cc2045d44).

Buona fortuna!

**Comment by ValeriaCom** [comment]
che stress stressante professò :D ora provvediamo! Grazie e buona serata!

**Comment by luca-lezzerini** [comment]
Lo chiudiamo questo ticket?!

**Comment by ValeriaCom** [comment]
Mi è sfuggito.
E poi è talmente tanto bello questo ticket che lo lascerei aperto almeno un paio d'anni e tramandarlo ai futuri malcapitati :D
